package com.epam.cashier.payments;

import com.epam.cashier.payments.banks.BankService;
import com.epam.cashier.payments.transactions.GetBalanceTransactionPayload;
import com.epam.cashier.payments.transactions.WithdrawalTransactionPayload;

import lombok.extern.slf4j.Slf4j;

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@Slf4j
public class VisaPaymentSystemService implements PaymentSystemService {
	private Map<String, BankService> banksRegistry;

	private final static Logger LOGGER = LoggerFactory.getLogger(VisaPaymentSystemService.class);

	public VisaPaymentSystemService(Map<String, BankService> banksRegistry) {
		this.banksRegistry = banksRegistry;
	}

	@Override
	public TransactionStatus processTransaction(WithdrawalTransactionPayload payload) {
		BankService bankService = banksRegistry.get(payload.getServiceCode());
		return bankService.processTransaction(payload);
	}

	@Override
	public BalanceInfo getBalanceInfo(GetBalanceTransactionPayload payload) {
		BankService bankService = banksRegistry.get(payload.getServiceCode());
		LOGGER.trace("Some info message from manually created logger");

		log.info("Some info message from autogenerated by Lombk logger");
		return bankService.getBalanceInfo(payload.getCardNumber());
	}
}
